addSbtPlugin("org.scoverage"    % "sbt-scoverage" % "1.6.0")
addSbtPlugin("org.scoverage"    % "sbt-coveralls" % "1.2.7")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"  % "2.3")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"       % "1.1.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-site"      % "1.4.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"  % "2.0.4")
